version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: omnify-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-omnify}
      POSTGRES_USER: ${POSTGRES_USER:-omnify}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-omnify}
    ports:
      - "5433:5432"
    volumes:
      - omnify_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnify"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: omnify-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: omnify-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: omnify-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: omnify-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  omnify_pg_data: